module.exports = {
    externs: [
      // 'externs/**/*.js',
    ],
    generate_exports: true,
    warning_level: 'VERBOSE',
    // jscomp_error: '*',
    jscomp_error: [
        'accessControls',
        'ambiguousFunctionDecl',
        'checkRegExp',
        'checkTypes',
        'checkVars',
        // 'conformanceViolations',
        'const',
        'constantProperty',
        'deprecated',
        'deprecatedAnnotations',
        // 'duplicateMessage',
        'es3',
        'es5Strict',
        'externsValidation',
        'fileoverviewTags',
        'functionParams',
        'globalThis',
        'internetExplorerChecks',
        'invalidCasts',
        'misplacedTypeAnnotation',
        // 'missingGetCssName',
        'missingOverride',
        'missingPolyfill',
        'missingProperties',
        'missingProvide',
        'missingRequire',
        'missingReturn',
        'moduleLoad',
        // 'msgDescriptions',
        'newCheckTypes',
        'nonStandardJsDocs',
        // 'missingSourcesWarnings',
        'polymer',
        // 'reportUnknownTypes',
        'suspiciousCode',
        'strictCheckTypes',
        'strictMissingProperties',
        'strictModuleDepCheck',
        'strictPrimitiveOperators',
        'typeInvalidation',
        'undefinedNames',
        'undefinedVars',
        'unknownDefines',
        'unusedLocalVariables',
        'unusedPrivateMembers',
        'uselessCode',
        'useOfGoogBase',
        'underscore',
        'visibility',
    ],
    language_in: 'ECMASCRIPT6_STRICT',
    language_out: 'ECMASCRIPT5',
    create_source_map: true,
    compilation_level: 'ADVANCED',
    outputWrapper: '(function(){%output%}).call(this)',
    // rewrite_polyfills: false,
    define: [
      'COMPILED=true',
      'goog.STRICT_MODE_COMPATIBLE=true',
      'goog.ENABLE_DEBUG_LOADER=false',
      'goog.DEBUG=false',
      // 'goog.asserts.ENABLE_ASSERTS=false',
    ]
}